---
apiVersion: v1
kind: Pod
metadata:
  name: webhook
  labels:
    app: webhook
  namespace: default
spec:
  restartPolicy: OnFailure
  containers:
    - name: webhook
      image: ketanmeh/dev:0.1
      imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: webhook
  namespace: default
spec:
  selector:
    app: webhook
  ports:
  - port: 443
    targetPort: 5000
