apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook
  namespace: default
webhooks:
  - name: webhook.default.svc
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1","v1beta1"]
    rules:
      - apiGroups: ["*"]
        resources: ["pods", "deployments", "deamonsets", "jobs", "cronjobs", "replicasets", "replicationcontrollers", "statefulsets"]
        apiVersions:
          - "*"
        operations:
          - CREATE
          - UPDATE
    clientConfig:
      service:
        name: webhook
        namespace: default
        path: /validate/
      caBundle: "${CA_PEM}"
